osx_image: xcode6.4
language: objective-c
cache:
  - bundler
  - cocoapods
before_install:
  - gem install cocoapods
podfile: Tests/Podfile
script: xctool -workspace Tests/Tests.xcworkspace -scheme Tests -sdk iphonesimulator build test
