osx_image: xcode7
cache:
  - bundler
  - cocoapods
language: swift
before_install:
  - gem install cocoapods
podfile: Tests/Podfile
script: xcodebuild -workspace Tests/Tests.xcworkspace -scheme Tests -sdk iphonesimulator build test
sudo: false
